/**
 * \file IfxGeth_PinMap_LFBGA436_COM.h
 * \brief GETH  details
 * \ingroup IfxLld_Geth
 *
 * \version iLLD_2_0_1_2_19
 * \copyright Copyright (c) 2022 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 * Version: MC_ACE_A3G_HWA_Ports/V9.1.2.0.14
 * Document: A3G_Pin_Assignment_v0.67_TO.xls
 *
 * \defgroup IfxLld_Geth_
 * \ingroup IfxLld_Geth
 * \defgroup IfxLld_Geth__Pinmap Variables Default
 * \ingroup IfxLld_Geth_
 * \defgroup IfxLld_Geth__PinTables Default
 * \ingroup IfxLld_Geth_
 */

#ifndef IFXGETH_PINMAP_LFBGA436_COM_H
#define IFXGETH_PINMAP_LFBGA436_COM_H 1

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "IfxGeth_PinMap.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

#define IFXGETH_PINMAP_NUM_MODULES            1

#define IFXGETH_PINMAP_COL_IN_NUM_ITEMS       3

#define IFXGETH_PINMAP_CRS_IN_NUM_ITEMS       4

#define IFXGETH_PINMAP_CRSDV_IN_NUM_ITEMS     4

#define IFXGETH_PINMAP_GREFCLK_IN_NUM_ITEMS   1

#define IFXGETH_PINMAP_MDC_OUT_NUM_ITEMS      6

#define IFXGETH_PINMAP_MDIO_INOUT_NUM_ITEMS   4

#define IFXGETH_PINMAP_PPS_OUT_NUM_ITEMS      4

#define IFXGETH_PINMAP_REFCLK_IN_NUM_ITEMS    4

#define IFXGETH_PINMAP_RXCLK_IN_NUM_ITEMS     4

#define IFXGETH_PINMAP_RXCTL_IN_NUM_ITEMS     1

#define IFXGETH_PINMAP_RXD_IN_NUM_ITEMS       9

#define IFXGETH_PINMAP_RXD_RGMII_IN_NUM_ITEMS 4

#define IFXGETH_PINMAP_RXDV_IN_NUM_ITEMS      4

#define IFXGETH_PINMAP_RXER_IN_NUM_ITEMS      4

#define IFXGETH_PINMAP_TXCLK_IN_NUM_ITEMS     4

#define IFXGETH_PINMAP_TXCLK_OUT_NUM_ITEMS    1

#define IFXGETH_PINMAP_TXCTL_OUT_NUM_ITEMS    1

#define IFXGETH_PINMAP_TXD_OUT_NUM_ITEMS      16

#define IFXGETH_PINMAP_TXEN_OUT_NUM_ITEMS     4

#define IFXGETH_PINMAP_TXER_OUT_NUM_ITEMS     2

/******************************************************************************/
/*-------------------Global Exported Variables/Constants----------------------*/
/******************************************************************************/
/** \brief Collision MII
 */
IFX_EXTERN IfxGeth_Col_In       IfxGeth0_COL_P15_8_IN;

/** \brief Collision MII
 */
IFX_EXTERN IfxGeth_Col_In       IfxGeth0_COL_P21_6_IN;

/** \brief Carrier Sense MII
 */
IFX_EXTERN IfxGeth_Crs_In       IfxGeth0_CRSC_P17_0_IN;

/** \brief Carrier Sense / Data Valid combi-signal for RMII (CRSDVA must only be used with REFCLKA)
 */
IFX_EXTERN IfxGeth_Crsdv_In     IfxGeth0_CRSDVC_P16_1_IN;

/** \brief Carrier Sense / Data Valid combi-signal for RMII (CRSDVA must only be used with REFCLKA)
 */
IFX_EXTERN IfxGeth_Crsdv_In     IfxGeth0_CRSDVD_P20_8_IN;

/** \brief Carrier Sense MII
 */
IFX_EXTERN IfxGeth_Crs_In       IfxGeth0_CRSD_P20_1_IN;

/** \brief Gigabit Reference Clock input for RGMII (125 MHz high precission)
 */
IFX_EXTERN IfxGeth_Grefclk_In   IfxGeth0_GREFCLK_P16_0_IN;

/** \brief MDIO Clock
 */
IFX_EXTERN IfxGeth_Mdc_Out      IfxGeth0_MDC0_P02_8_OUT;

/** \brief MDIO Clock
 */
IFX_EXTERN IfxGeth_Mdc_Out      IfxGeth0_MDC0_P16_11_OUT;

/** \brief MDIO Clock
 */
IFX_EXTERN IfxGeth_Mdc_Out      IfxGeth0_MDC0_P21_2_OUT;

/** \brief MDIO Clock
 */
IFX_EXTERN IfxGeth_Mdc_Out      IfxGeth0_MDC1_P02_8_OUT;

/** \brief MDIO Clock
 */
IFX_EXTERN IfxGeth_Mdc_Out      IfxGeth0_MDC1_P16_11_OUT;

/** \brief MDIO Clock
 */
IFX_EXTERN IfxGeth_Mdc_Out      IfxGeth0_MDC1_P21_2_OUT;

/** \brief MDIO output and MDIO input
 */
IFX_EXTERN IfxGeth_Mdio_InOut   IfxGeth0_MDIO_P00_0_INOUT;

/** \brief MDIO output and MDIO input
 */
IFX_EXTERN IfxGeth_Mdio_InOut   IfxGeth0_MDIO_P16_14_INOUT;

/** \brief MDIO output and MDIO input
 */
IFX_EXTERN IfxGeth_Mdio_InOut   IfxGeth0_MDIO_P21_3_INOUT;

/** \brief GETH MAC0 Precision Timing Interrupt trigger
 */
IFX_EXTERN IfxGeth_Pps_Out      IfxGeth0_PPS_P14_2_OUT;

/** \brief GETH MAC1 Precision Timing Interrupt trigger
 */
IFX_EXTERN IfxGeth_Pps_Out      IfxGeth0_PPS_P14_3_OUT;

/** \brief GETH MAC0 Precision Timing Interrupt trigger
 */
IFX_EXTERN IfxGeth_Pps_Out      IfxGeth0_PPS_P14_4_OUT;

/** \brief GETH MAC1 Precision Timing Interrupt trigger
 */
IFX_EXTERN IfxGeth_Pps_Out      IfxGeth0_PPS_P14_8_OUT;

/** \brief Reference Clock input for RMII (50 MHz)
 */
IFX_EXTERN IfxGeth_Refclk_In    IfxGeth0_REFCLKB_P21_4_IN;

/** \brief Reference Clock input for RMII (50 MHz)
 */
IFX_EXTERN IfxGeth_Refclk_In    IfxGeth0_REFCLKD_P16_2_IN;

/** \brief Receive Clock MII
 */
IFX_EXTERN IfxGeth_Rxclk_In     IfxGeth0_RXCLKB_P21_4_IN;

/** \brief Receive Clock MII
 */
IFX_EXTERN IfxGeth_Rxclk_In     IfxGeth0_RXCLKD_P16_2_IN;

/** \brief Receive Clock RGMII
 */
IFX_EXTERN IfxGeth_Rxclk_In     IfxGeth0_RXCLK_RGMII_P16_2_IN;

/** \brief Receive Control for RGMII
 */
IFX_EXTERN IfxGeth_Rxctl_In     IfxGeth0_RXCTL_P16_1_IN;

/** \brief Receive Data 0 MII, RMII (RXD0A must only be used with REFCLKA)
 */
IFX_EXTERN IfxGeth_Rxd_In       IfxGeth0_RXD0B_P16_4_IN;

/** \brief Receive Data 0 MII, RMII (RXD0A must only be used with REFCLKA)
 */
IFX_EXTERN IfxGeth_Rxd_In       IfxGeth0_RXD0C_P20_12_IN;

/** \brief Receive Data 1 MII and RMII (RXD1A must only be used with REFCLKA)
 */
IFX_EXTERN IfxGeth_Rxd_In       IfxGeth0_RXD1B_P16_3_IN;

/** \brief Receive Data 1 MII and RMII (RXD1A must only be used with REFCLKA)
 */
IFX_EXTERN IfxGeth_Rxd_In       IfxGeth0_RXD1C_P20_11_IN;

/** \brief Receive Data 2 MII
 */
IFX_EXTERN IfxGeth_Rxd_In       IfxGeth0_RXD2B_P16_5_IN;

/** \brief Receive Data 2 MII
 */
IFX_EXTERN IfxGeth_Rxd_In       IfxGeth0_RXD2C_P20_13_IN;

/** \brief Receive Data 3 MII
 */
IFX_EXTERN IfxGeth_Rxd_In       IfxGeth0_RXD3B_P16_7_IN;

/** \brief Receive Data 3 MII
 */
IFX_EXTERN IfxGeth_Rxd_In       IfxGeth0_RXD3C_P20_14_IN;

/** \brief Receive Data Valid MII
 */
IFX_EXTERN IfxGeth_Rxdv_In      IfxGeth0_RXDVC_P16_1_IN;

/** \brief Receive Data Valid MII
 */
IFX_EXTERN IfxGeth_Rxdv_In      IfxGeth0_RXDVD_P20_8_IN;

/** \brief Receive data RGMII (Receive data connected directly to pads)
 */
IFX_EXTERN IfxGeth_Rxd_rgmii_In IfxGeth0_RXD_RGMII0_P16_4_IN;

/** \brief Receive data RGMII (Receive data connected directly to pads)
 */
IFX_EXTERN IfxGeth_Rxd_rgmii_In IfxGeth0_RXD_RGMII1_P16_3_IN;

/** \brief Receive data RGMII (Receive data connected directly to pads)
 */
IFX_EXTERN IfxGeth_Rxd_rgmii_In IfxGeth0_RXD_RGMII2_P16_5_IN;

/** \brief Receive data RGMII (Receive data connected directly to pads)
 */
IFX_EXTERN IfxGeth_Rxd_rgmii_In IfxGeth0_RXD_RGMII3_P16_7_IN;

/** \brief Receive Error MII
 */
IFX_EXTERN IfxGeth_Rxer_In      IfxGeth0_RXERB_P21_7_IN;

/** \brief Receive Error MII
 */
IFX_EXTERN IfxGeth_Rxer_In      IfxGeth0_RXERC_P10_0_IN;

/** \brief Receive Error MII
 */
IFX_EXTERN IfxGeth_Rxer_In      IfxGeth0_RXERD_P17_1_IN;

/** \brief Transmit Clock Input for MII
 */
IFX_EXTERN IfxGeth_Txclk_In     IfxGeth0_TXCLKC_P16_0_IN;

/** \brief Transmit Clock Input for MII
 */
IFX_EXTERN IfxGeth_Txclk_In     IfxGeth0_TXCLKD_P20_3_IN;

/** \brief
 */
IFX_EXTERN IfxGeth_Txclk_Out    IfxGeth0_TXCLK_P16_12_OUT;

/** \brief Transmit Control for RGMII
 */
IFX_EXTERN IfxGeth_Txctl_Out    IfxGeth0_TXCTL_P16_13_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_MII_P16_10_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_MII_P16_6_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_MII_P16_8_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_MII_P16_9_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_MII_P20_0_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_MII_P20_10_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_MII_P20_7_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_MII_P20_9_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_RGMII0_P16_6_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_RGMII1_P16_8_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_RGMII2_P16_9_OUT;

/** \brief Transmit data
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_RGMII3_P16_10_OUT;

/** \brief Transmit data (dedicated for Port 16)
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_RMII_P16_6_OUT;

/** \brief Transmit data (dedicated for Port 16)
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_RMII_P16_8_OUT;

/** \brief Transmit data (dedicated for Port20/21)
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_RMII_P20_10_OUT;

/** \brief Transmit data (dedicated for Port20/21)
 */
IFX_EXTERN IfxGeth_Txd_Out      IfxGeth0_TXD_RMII_P20_9_OUT;

/** \brief Transmit Enable MII
 */
IFX_EXTERN IfxGeth_Txen_Out     IfxGeth0_TXEN_MII_P16_13_OUT;

/** \brief Transmit Enable MII
 */
IFX_EXTERN IfxGeth_Txen_Out     IfxGeth0_TXEN_MII_P21_5_OUT;

/** \brief Transmit Enable RMII (dedicated for Port 16)
 */
IFX_EXTERN IfxGeth_Txen_Out     IfxGeth0_TXEN_RMII_P16_13_OUT;

/** \brief Transmit Enable RMII (dedicated for Port20/21)
 */
IFX_EXTERN IfxGeth_Txen_Out     IfxGeth0_TXEN_RMII_P21_5_OUT;

/** \brief Transmit Error MII
 */
IFX_EXTERN IfxGeth_Txer_Out     IfxGeth0_TXER_P16_12_OUT;

/** \brief Transmit Error MII
 */
IFX_EXTERN IfxGeth_Txer_Out     IfxGeth0_TXER_P20_6_OUT;

/** \addtogroup IfxLld_Geth__PinTables
 * \{ */

/******************************************************************************/
/*-------------------Global Exported Variables/Constants----------------------*/
/******************************************************************************/
/** \brief IfxGeth_Col_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Col_In       *IfxGeth_Col_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_COL_IN_NUM_ITEMS];

/** \brief IfxGeth_Crs_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Crs_In       *IfxGeth_Crs_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_CRS_IN_NUM_ITEMS];

/** \brief IfxGeth_Crsdv_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Crsdv_In     *IfxGeth_Crsdv_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_CRSDV_IN_NUM_ITEMS];

/** \brief IfxGeth_Grefclk_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Grefclk_In   *IfxGeth_Grefclk_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_GREFCLK_IN_NUM_ITEMS];

/** \brief IfxGeth_Mdc_Out Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Mdc_Out      *IfxGeth_Mdc_Out_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_MDC_OUT_NUM_ITEMS];

/** \brief IfxGeth_Mdio_InOut Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Mdio_InOut   *IfxGeth_Mdio_InOut_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_MDIO_INOUT_NUM_ITEMS];

/** \brief IfxGeth_Pps_Out Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Pps_Out      *IfxGeth_Pps_Out_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_PPS_OUT_NUM_ITEMS];

/** \brief IfxGeth_Refclk_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Refclk_In    *IfxGeth_Refclk_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_REFCLK_IN_NUM_ITEMS];

/** \brief IfxGeth_Rxclk_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Rxclk_In     *IfxGeth_Rxclk_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_RXCLK_IN_NUM_ITEMS];

/** \brief IfxGeth_Rxctl_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Rxctl_In     *IfxGeth_Rxctl_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_RXCTL_IN_NUM_ITEMS];

/** \brief IfxGeth_Rxd_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Rxd_In       *IfxGeth_Rxd_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_RXD_IN_NUM_ITEMS];

/** \brief IfxGeth_Rxd_rgmii_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Rxd_rgmii_In *IfxGeth_Rxd_rgmii_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_RXD_RGMII_IN_NUM_ITEMS];

/** \brief IfxGeth_Rxdv_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Rxdv_In      *IfxGeth_Rxdv_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_RXDV_IN_NUM_ITEMS];

/** \brief IfxGeth_Rxer_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Rxer_In      *IfxGeth_Rxer_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_RXER_IN_NUM_ITEMS];

/** \brief IfxGeth_Txclk_In Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Txclk_In     *IfxGeth_Txclk_In_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_TXCLK_IN_NUM_ITEMS];

/** \brief IfxGeth_Txclk_Out Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Txclk_Out    *IfxGeth_Txclk_Out_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_TXCLK_OUT_NUM_ITEMS];

/** \brief IfxGeth_Txctl_Out Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Txctl_Out    *IfxGeth_Txctl_Out_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_TXCTL_OUT_NUM_ITEMS];

/** \brief IfxGeth_Txd_Out Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Txd_Out      *IfxGeth_Txd_Out_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_TXD_OUT_NUM_ITEMS];

/** \brief IfxGeth_Txen_Out Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Txen_Out     *IfxGeth_Txen_Out_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_TXEN_OUT_NUM_ITEMS];

/** \brief IfxGeth_Txer_Out Table
 */
IFX_EXTERN IFX_CONST IfxGeth_Txer_Out     *IfxGeth_Txer_Out_pinTable[IFXGETH_PINMAP_NUM_MODULES][IFXGETH_PINMAP_TXER_OUT_NUM_ITEMS];

/** \} */

#endif /* IFXGETH_PINMAP_LFBGA436_COM_H */
