/**
 * \file IfxCsrom_reg.h
 * \brief
 * \copyright Copyright (c) 2020 Infineon Technologies AG. All rights reserved.
 *
 *
 * Version: MC_ACE_A3G_HSI_CSRM/V0.1.3.1.1
 * Specification: latest @ 2020-07-15, instance sheet @ MC_A3G_TC49x : V9.1.3.1.0 
 * MAY BE CHANGED BY USER [yes/no]: No
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * \defgroup IfxSfr_Csrom_Registers_Cfg Csrom address
 * \ingroup IfxSfr_Csrom_Registers
 * 
 * \defgroup IfxSfr_Csrom_Registers_Cfg_BaseAddress Base address
 * \ingroup IfxSfr_Csrom_Registers_Cfg
 *
 * \defgroup IfxSfr_Csrom_Registers_Cfg_Csrom 2-CSROM
 * \ingroup IfxSfr_Csrom_Registers_Cfg
 *
 *
 */
#ifndef IFXCSROM_REG_H
#define IFXCSROM_REG_H 1
/******************************************************************************/
#include "IfxCsrom_regdef.h"
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/

/** \addtogroup IfxSfr_Csrom_Registers_Cfg_BaseAddress
 * \{  */

/** \brief CSROM object */
#define MODULE_CSROM /*lint --e(923, 9078)*/ ((*(Ifx_CSROM*)0x8FFE0000u))
/** \}  */


/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_Csrom_Registers_Cfg_Csrom
 * \{  */
/** \brief C000, BootROM of the CPUcs */
#define CSROM_NC_CSROM ((void*)0xAFFEC000u)
#define CSROM_NC_CSROM_SIZE (0x4000u)
/** \brief C000, BootROM of the CPUcs */
#define CSROM_CSROM ((void*)0x8FFEC000u)
#define CSROM_CSROM_SIZE (0x4000u)

/** \}  */

/******************************************************************************/

/******************************************************************************/

#endif /* IFXCSROM_REG_H */
