/**
 * \file IfxLli_reg.h
 * \brief
 * \copyright Copyright (c) 2021 Infineon Technologies AG. All rights reserved.
 *
 *
 * Version: MC_ACE_A3G_HSI_LLI/V0.1.1.1.1
 * Specification: latest @ 2021-08-22 instance sheet @ MC_A3G_TC49x : V9.1.6.1.0 
 * MAY BE CHANGED BY USER [yes/no]: No
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * \defgroup IfxSfr_Lli_Registers_Cfg Lli address
 * \ingroup IfxSfr_Lli_Registers
 * 
 * \defgroup IfxSfr_Lli_Registers_Cfg_BaseAddress Base address
 * \ingroup IfxSfr_Lli_Registers_Cfg
 *
 * \defgroup IfxSfr_Lli_Registers_Cfg_Lli0 2-LLI0
 * \ingroup IfxSfr_Lli_Registers_Cfg
 *
 *
 */
#ifndef IFXLLI_REG_H
#define IFXLLI_REG_H 1
/******************************************************************************/
#include "IfxLli_regdef.h"
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/

/** \addtogroup IfxSfr_Lli_Registers_Cfg_BaseAddress
 * \{  */

/** \brief LLI object */
#define MODULE_LLI0 /*lint --e(923, 9078)*/ ((*(Ifx_LLI*)0xF9828000u))
/** \}  */


/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_Lli_Registers_Cfg_Lli0
 * \{  */
/** \brief C, Alarm Event */
#define LLI0_LLI_ALEV /*lint --e(923, 9078)*/ (*(volatile Ifx_LLI_LLI_ALEV*)0xF982800Cu)

/** \brief 10, Alarm Clear */
#define LLI0_LLI_ALCLR /*lint --e(923, 9078)*/ (*(volatile Ifx_LLI_LLI_ALCLR*)0xF9828010u)

/** \brief 14, Error injection from S2L master interface */
#define LLI0_LLI_MEGEN /*lint --e(923, 9078)*/ (*(volatile Ifx_LLI_LLI_MEGEN*)0xF9828014u)

/** \brief 18, Error injection from eGTM wrapper slave interface */
#define LLI0_LLI_SEGEN /*lint --e(923, 9078)*/ (*(volatile Ifx_LLI_LLI_SEGEN*)0xF9828018u)


/** \}  */

/******************************************************************************/

/******************************************************************************/

#endif /* IFXLLI_REG_H */
