/**
 * \file IfxPkc_reg.h
 * \brief
 * \copyright Copyright (c) 2021 Infineon Technologies AG. All rights reserved.
 *
 *
 * Version: MC_ACE_A3G_HSI_CSRM/V0.1.3.1.8
 * Specification: latest @ 2021-07-15 instance sheet @ MC_A3G_TC49x : V9.1.6.1.0 
 * MAY BE CHANGED BY USER [yes/no]: No
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * \defgroup IfxSfr_Pkc_Registers_Cfg Pkc address
 * \ingroup IfxSfr_Pkc_Registers
 * 
 * \defgroup IfxSfr_Pkc_Registers_Cfg_BaseAddress Base address
 * \ingroup IfxSfr_Pkc_Registers_Cfg
 *
 * \defgroup IfxSfr_Pkc_Registers_Cfg_Pkc 2-PKC
 * \ingroup IfxSfr_Pkc_Registers_Cfg
 *
 *
 */
#ifndef IFXPKC_REG_H
#define IFXPKC_REG_H 1
/******************************************************************************/
#include "IfxPkc_regdef.h"
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/

/** \addtogroup IfxSfr_Pkc_Registers_Cfg_BaseAddress
 * \{  */

/** \brief PKC object */
#define MODULE_PKC /*lint --e(923, 9078)*/ ((*(Ifx_PKC*)0xF6010000u))
/** \}  */


/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_Pkc_Registers_Cfg_Pkc
 * \{  */
/** \brief 0, Ucode ROM */
#define PKC_UCODEROM ((void*)0xF6012000u)
#define PKC_UCODEROM_SIZE (0x2000u)

/** \brief 2000, Data RAM */
#define PKC_DATARAM ((void*)0xF6014000u)
#define PKC_DATARAM_SIZE (0x2000u)

/** \brief 0, Clock control register */
#define PKC_CLC /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_CLC*)0xF6010000u)

/** \brief 8, Module identification register */
#define PKC_ID /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_ID*)0xF6010008u)

/** \brief 20, PROT register Endinit */
#define PKC_PROTE /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_PROT*)0xF6010020u)

/** \brief 24, PROT register Safe Endinit */
#define PKC_PROTSE /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_PROT*)0xF6010024u)

/** \brief 40, Write access enable register A */
#define PKC_ACCEN_WRA /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_ACCEN_WRA*)0xF6010040u)

/** \brief 44, Write access enable register B */
#define PKC_ACCEN_WRB /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_ACCEN_WRB*)0xF6010044u)

/** \brief 48, Read access enable register A */
#define PKC_ACCEN_RDA /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_ACCEN_RDA*)0xF6010048u)

/** \brief 4C, Read access enable register B */
#define PKC_ACCEN_RDB /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_ACCEN_RDB*)0xF601004Cu)

/** \brief 50, VM access enable register */
#define PKC_ACCEN_VM /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_ACCEN_VM*)0xF6010050u)

/** \brief 54, PRS access enable register */
#define PKC_ACCEN_PRS /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_ACCEN_PRS*)0xF6010054u)

/** \brief 0, Pointer register */
#define PKC_PTR /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_PTR*)0xF6010100u)

/** \brief 4, Command register */
#define PKC_CMD /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_CMD*)0xF6010104u)

/** \brief 8, Control register */
#define PKC_CTRL /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_CTRL*)0xF6010108u)

/** \brief C, Status register */
#define PKC_STAT /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_STAT*)0xF601010Cu)

/** \brief 14, Timer register */
#define PKC_TIMER /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_TIMER*)0xF6010114u)

/** \brief 18, Hardware configuration register */
#define PKC_HWCONFIG /*lint --e(923, 9078)*/ (*(volatile Ifx_PKC_HWCONFIG*)0xF6010118u)


/** \}  */

/******************************************************************************/

/******************************************************************************/

#endif /* IFXPKC_REG_H */
