/**
 * \file IfxVmt_cfg.c
 * \brief Vmt on-chip implementation data
 *
 * \version iLLD_2_0_1_2_19
 * \copyright Copyright (c) 2021 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "IfxVmt_cfg.h"

/******************************************************************************/
/*-----------------------Exported Variables/Constants-------------------------*/
/******************************************************************************/

IFX_CONST IfxVmt_SramItem IfxVmt_sramTable[IFXVMT_NUM_MBIST_TABLE_ITEMS] = {
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Dspr0 */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Dlmu */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Dspr0 */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Dlmu */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Dspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Dlmu */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Dspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Dlmu */
    {1 * 4, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_dma0 */
    {1 * 2, 128, 0, 0, 0}, /**< \brief IfxVmt_MbistSel_mcds4pTbuf */
    {1 * 4, 32,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_mcds4pLut */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 4, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_dma1 */
    {1 * 2, 128, 0, 0, 0}, /**< \brief IfxVmt_MbistSel_mcds2pTbuf */
    {1 * 2, 32,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_mcds2pLut */
    {1 * 1, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cssKeyattr */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cssKeystore */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cssFifo0 */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cssFifo1 */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cssFifo2 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Dspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Dlmu */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Dspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Dlmu */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mod9 */
    {2 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mod10 */
    {1 * 2, 16,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_hsphyPcs0 */
    {1 * 2, 16,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_hsphyPcs1 */
    {1 * 1, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_pcieDmaRbuf */
    {1 * 1, 46,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_pcieRxDq */
    {1 * 2, 85,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_pcieRxHq */
    {1 * 1, 47,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_pcieRetryBuf */
    {1 * 1, 87,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_pcieMcplBuf */
    {1 * 4, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_ethermacAxi */
    {1 * 1, 72,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermacDmi */
    {1 * 1, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac0Gcl */
    {1 * 1, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac1Gcl */
    {1 * 1, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac0RxEven */
    {1 * 1, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac0RxOdd */
    {1 * 1, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac1RxEven */
    {1 * 1, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac1RxOdd */
    {1 * 1, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac0TxEven */
    {1 * 1, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac0TxOdd */
    {1 * 1, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac1TxEven */
    {1 * 1, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac1TxOdd */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan0 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan1 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan2 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan3 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan4 */
    {1 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_dreRam */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_sdmmc */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu0 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu1 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu2 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu3 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu4 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu5 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu6 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu7 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_psi5 */
    {1 * 2, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray0Obf */
    {1 * 2, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray1Obf */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray0IbfTbf */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray1IbfTbf */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray0Mbf */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray1Mbf */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmDspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmDtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmPspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmPtag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmDlmu */
    {1 * 2, 68,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_mod8 */
    {1 * 1, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_scrXram */
    {1 * 1, 8,   6, 0, 1}, /**< \brief IfxVmt_MbistSel_scrIram */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 4, 30,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuIctag */
    {1 * 4, 80,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuIcdata */
    {1 * 4, 28,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuDctag */
    {1 * 4, 80,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuDcdata */
    {1 * 2, 68,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuBc */
    {1 * 2, 16,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuPt */
    {1 * 1, 64,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuRttint */
    {1 * 8, 24,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuVecmem0 */
    {1 * 8, 24,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuVecmem1 */
    {1 * 8, 24,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuVecmem2 */
    {1 * 8, 24,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuVecmem3 */
    {1 * 8, 73,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ppuLlmram */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 1, 24,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_gtmDpll1a */
    {1 * 1, 24,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_gtmDpll1b */
    {1 * 1, 24,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_gtmDpll2 */
    {1 * 3, 29,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_gtmFifo */
    {1 * 5, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_gtmMcsP0 */
    {1 * 5, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_gtmMcsD0 */
    {1 * 5, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_gtmMcsP1 */
    {1 * 5, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_gtmMcsD1 */
    {1 * 4, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_cdsp0Data */
    {2 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cdsp0Prog */
    {1 * 4, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_cdsp4Data */
    {2 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cdsp4Prog */
    {1 * 4, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_cdsp8Data */
    {2 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cdsp8Prog */
    {1 * 4, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_cdsp12Data */
    {2 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cdsp12Prog */
    {1 * 2, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_cdsp16Data */
    {2 * 2, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cdsp16Prog */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
};
